# Generated by Django 4.2.5 on 2023-09-05 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('type', models.CharField(max_length=60)),
                ('rent_rate_per_day', models.DecimalField(decimal_places=2, max_digits=8)),
                ('mileage', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
    ]
