# Generated by Django 4.2.5 on 2023-09-05 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentcar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Cars', 'verbose_name_plural': 'Car'},
        ),
    ]
