# Generated by Django 4.2.5 on 2023-09-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcar', '0002_alter_car_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_image',
            field=models.ImageField(default=None, upload_to='cars/%Y/%m'),
        ),
    ]
